### ISSUE TITLE
Installation error. Could you please help me with this?

### ISSUE THREAD

**Issue by Jaswanth720** [dhanababum/accessdb#1]
(base) C:\Users\jaswanthnaidu.gade\Downloads>pip install accessdb
Collecting accessdb
  Using cached https://files.pythonhosted.org/packages/56/fd/2c107bc8b0004630ae556aa68d85390636d419369ddeebab27e6db98fb5a/accessdb-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JASWAN~1.GAD\AppData\Local\Temp\pip-install-d6dz20xo\accessdb\setup.py", line 8, in <module>
        with open('README.md') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in

**Comment by Jaswanth720** [comment]
Fixed!
